"""Central configuration loaded from environment variables.

All tunables (database URL, master key, lockout thresholds, WebAuthn relying
party, Anthropic model) are resolved here so the rest of the codebase reads
from a single typed object instead of scattered ``os.environ`` lookups.
"""

from __future__ import annotations

import base64
import os
from dataclasses import dataclass, field

from dotenv import load_dotenv

# Load a local .env if present. In production these come from the real
# environment (e.g. Streamlit Cloud secrets) so a missing file is fine.
load_dotenv()


def _get_bool(name: str, default: bool = False) -> bool:
    raw = os.environ.get(name)
    if raw is None:
        return default
    return raw.strip().lower() in {"1", "true", "yes", "on"}


def _get_int(name: str, default: int) -> int:
    raw = os.environ.get(name)
    if raw is None or raw.strip() == "":
        return default
    return int(raw)


@dataclass
class Config:
    """Strongly-typed view over the process environment."""

    secret_key: str = field(default_factory=lambda: os.environ.get("SECRET_KEY", "dev-secret"))
    database_url: str = field(default_factory=lambda: os.environ.get("DATABASE_URL", "sqlite:///mfa.db"))

    # Raw base64 master key (32 bytes when decoded). May be empty in tests,
    # in which case an ephemeral key is generated by the vault.
    master_key_b64: str = field(default_factory=lambda: os.environ.get("MASTER_KEY", ""))

    # WebAuthn relying party.
    webauthn_rp_id: str = field(default_factory=lambda: os.environ.get("WEBAUTHN_RP_ID", "localhost"))
    webauthn_rp_name: str = field(default_factory=lambda: os.environ.get("WEBAUTHN_RP_NAME", "MFA Capstone Server"))
    webauthn_rp_origin: str = field(
        default_factory=lambda: os.environ.get("WEBAUTHN_RP_ORIGIN", "http://localhost:5000")
    )

    # Anthropic / Claude.
    anthropic_api_key: str = field(default_factory=lambda: os.environ.get("ANTHROPIC_API_KEY", ""))
    anthropic_model: str = field(
        default_factory=lambda: os.environ.get("ANTHROPIC_MODEL", "claude-3-5-haiku-latest")
    )

    # Lockout policy.
    lockout_max_failures: int = field(default_factory=lambda: _get_int("LOCKOUT_MAX_FAILURES", 5))
    lockout_window_seconds: int = field(default_factory=lambda: _get_int("LOCKOUT_WINDOW_SECONDS", 300))
    lockout_duration_seconds: int = field(default_factory=lambda: _get_int("LOCKOUT_DURATION_SECONDS", 900))

    # Dashboard wiring.
    api_base_url: str = field(default_factory=lambda: os.environ.get("API_BASE_URL", "http://localhost:5000"))
    embedded: bool = field(default_factory=lambda: _get_bool("EMBEDDED", False))

    def master_key_bytes(self) -> bytes | None:
        """Return the decoded 32-byte master key, or ``None`` if unset.

        The vault treats ``None`` as "generate an ephemeral key" which is only
        appropriate for tests; production deployments MUST set ``MASTER_KEY``.
        """
        if not self.master_key_b64:
            return None
        key = base64.b64decode(self.master_key_b64)
        if len(key) != 32:
            raise ValueError(
                "MASTER_KEY must decode to exactly 32 bytes for AES-256; "
                f"got {len(key)} bytes."
            )
        return key


# Singleton-style accessor. Tests can construct their own Config() if needed.
config = Config()
